// constants/theme.js

module.exports = {
  colors: {
    'surface-container-highest': '#d3e4fe',
    'tertiary-container': '#007d55',
    'on-error': '#ffffff',
    'text-primary': 'hsl(222, 47%, 11%)',
    'primary-fixed': '#dbe1ff',
    'on-surface-variant': '#434655',
    destructive: 'hsl(350, 89%, 60%)',
    surface: 'hsl(0, 0%, 100%)',
    'surface-container-low': '#eff4ff',
    'on-tertiary-container': '#bdffdb',
    'secondary-fixed': '#e9ddff',
    primary: 'hsl(221, 83%, 53%)',
    'secondary-container': '#8455ef',
    'surface-elevated': 'hsl(0, 0%, 100%)',
    'surface-variant': '#d3e4fe',
    'primary-fixed-dim': '#b4c5ff',
    success: 'hsl(161, 64%, 39%)',
    'on-success': '#ffffff',
    'on-secondary-fixed': '#23005c',
    'on-background': '#0b1c30',
    'on-tertiary-fixed': '#002113',
    error: '#ba1a1a',
    'secondary-fixed-dim': '#d0bcff',
    'inverse-primary': '#b4c5ff',
    'surface-container': '#e5eeff',
    'on-tertiary': '#ffffff',
    'on-primary-fixed': '#00174b',
    tertiary: '#006242',
    'on-secondary-fixed-variant': '#5516be',
    outline: '#737686',
    warning: 'hsl(38, 92%, 50%)',
    'on-warning': '#0b1c30',
    'surface-container-high': '#dce9ff',
    'error-container': '#ffdad6',
    'outline-variant': '#c3c6d7',
    info: 'hsl(262, 83%, 66%)',
    'on-info': '#ffffff',
    'text-secondary': 'hsl(215, 16%, 47%)',
    'on-secondary-container': '#fffbff',
    'on-error-container': '#93000a',
    background: 'hsl(210, 40%, 98%)',
    'on-secondary': '#ffffff',
    'text-muted': 'hsl(215, 20%, 65%)',
    'on-primary-fixed-variant': '#003ea8',
    secondary: '#6b38d4',
    'tertiary-fixed-dim': '#4edea3',
    'on-surface': '#0b1c30',
    'surface-bright': '#f8f9ff',
    'primary-container': '#2563eb',
    'inverse-surface': '#213145',
    'on-primary': '#ffffff',
    'tertiary-fixed': '#6ffbbe',
    'surface-container-lowest': '#ffffff',
    border: 'hsl(214, 32%, 91%)',
    'on-primary-container': '#eeefff',
    'surface-dim': '#cbdbf5',
    'inverse-on-surface': '#eaf1ff',
    'surface-tint': '#0053db',
    'on-tertiary-fixed-variant': '#005236',
  },
  iconSize: {
    sm: 16,
    md: 20,
    lg: 24,
    xl: 32,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 40,
    base: 4,
    gutter: 12,
    '5': 20,
    'container-max': 1280,
  },
  radius: {
    DEFAULT: 4, // 0.25rem = 4px
    lg: 8,      // 0.5rem = 8px
    xl: 12,     // 0.75rem = 12px
    full: 9999,
  }
};