
services:
  app:
    container_name: app-juragantitip
    build:
      context: .
      # args:
      #   VITE_API_URL: ${VITE_API_URL}
      #   DATABASE_URL: ${DATABASE_URL}
      #   SHADOW_DATABASE_URL: ${SHADOW_DATABASE_URL}
    networks:
      - caddy_net
    # expose:
    #   - "3001"
    # env_file:
    #   - .env
    restart: unless-stopped
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"


  # caddy:
  #   image: caddy:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   restart: always




networks:
  caddy_net:
    external: true