/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#d3e4fe',
        'tertiary-container': '#007d55',
        'on-error': '#ffffff',
        'text-primary': 'hsl(222, 47%, 11%)',
        'primary-fixed': '#dbe1ff',
        'on-surface-variant': '#434655',
        destructive: 'hsl(350, 89%, 60%)',
        surface: 'hsl(0, 0%, 100%)',
        'surface-container-low': '#eff4ff',
        'on-tertiary-container': '#bdffdb',
        'secondary-fixed': '#e9ddff',
        primary: 'hsl(221, 83%, 53%)',
        'secondary-container': '#8455ef',
        'surface-elevated': 'hsl(0, 0%, 100%)',
        'surface-variant': '#d3e4fe',
        'primary-fixed-dim': '#b4c5ff',
        success: 'hsl(161, 64%, 39%)',
        'on-success': '#ffffff',
        'on-secondary-fixed': '#23005c',
        'on-background': '#0b1c30',
        'on-tertiary-fixed': '#002113',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#d0bcff',
        'inverse-primary': '#b4c5ff',
        'surface-container': '#e5eeff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#00174b',
        tertiary: '#006242',
        'on-secondary-fixed-variant': '#5516be',
        outline: '#737686',
        warning: 'hsl(38, 92%, 50%)',
        'on-warning': '#0b1c30',
        'surface-container-high': '#dce9ff',
        'error-container': '#ffdad6',
        'outline-variant': '#c3c6d7',
        info: 'hsl(262, 83%, 66%)',
        'on-info': '#ffffff',
        'text-secondary': 'hsl(215, 16%, 47%)',
        'on-secondary-container': '#fffbff',
        'on-error-container': '#93000a',
        background: 'hsl(210, 40%, 98%)',
        'on-secondary': '#ffffff',
        'text-muted': 'hsl(215, 20%, 65%)',
        'on-primary-fixed-variant': '#003ea8',
        secondary: '#6b38d4',
        'tertiary-fixed-dim': '#4edea3',
        'on-surface': '#0b1c30',
        'surface-bright': '#f8f9ff',
        'primary-container': '#2563eb',
        'inverse-surface': '#213145',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#6ffbbe',
        'surface-container-lowest': '#ffffff',
        border: 'hsl(214, 32%, 91%)',
        'on-primary-container': '#eeefff',
        'surface-dim': '#cbdbf5',
        'inverse-on-surface': '#eaf1ff',
        'surface-tint': '#0053db',
        'on-tertiary-fixed-variant': '#005236',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        base: '4px',
        gutter: '12px',
        '5': '20px',
        'container-max': '1280px',
      },
      fontFamily: {
        'data-lg': ['JetBrains Mono', 'monospace'],
        'data-md': ['JetBrains Mono', 'monospace'],
        'data-sm': ['JetBrains Mono', 'monospace'],
        h1: ['Inter', 'sans-serif'],
        h2: ['Inter', 'sans-serif'],
        h3: ['Inter', 'sans-serif'],
        overline: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'data-lg': ['18px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '600' }],
        'data-md': ['14px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        'data-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '400' }],
        body: ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        h1: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        h2: ['20px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '600' }],
        overline: ['11px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        display: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        caption: ['12px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
  ],
}

