import { z } from 'zod';

export const SETTINGS_VALIDATION_RULES = {
  STOCK_THRESHOLD_MIN: 1,
  STOCK_THRESHOLD_MAX: 1000,
  CATEGORY_MIN: 3,
  CATEGORY_MAX: 30,
  OVERDUE_DAYS_MIN: 1,
  OVERDUE_DAYS_MAX: 300,
};

const categoryLabelsSchema = z.object({
  "1": z.string().min(SETTINGS_VALIDATION_RULES.CATEGORY_MIN, `Min. ${SETTINGS_VALIDATION_RULES.CATEGORY_MIN} kar`).max(SETTINGS_VALIDATION_RULES.CATEGORY_MAX, `Maks. ${SETTINGS_VALIDATION_RULES.CATEGORY_MAX} kar`),
  "2": z.string().min(SETTINGS_VALIDATION_RULES.CATEGORY_MIN, `Min. ${SETTINGS_VALIDATION_RULES.CATEGORY_MIN} kar`).max(SETTINGS_VALIDATION_RULES.CATEGORY_MAX, `Maks. ${SETTINGS_VALIDATION_RULES.CATEGORY_MAX} kar`),
  "3": z.string().min(SETTINGS_VALIDATION_RULES.CATEGORY_MIN, `Min. ${SETTINGS_VALIDATION_RULES.CATEGORY_MIN} kar`).max(SETTINGS_VALIDATION_RULES.CATEGORY_MAX, `Maks. ${SETTINGS_VALIDATION_RULES.CATEGORY_MAX} kar`),
  "4": z.string().min(SETTINGS_VALIDATION_RULES.CATEGORY_MIN, `Min. ${SETTINGS_VALIDATION_RULES.CATEGORY_MIN} kar`).max(SETTINGS_VALIDATION_RULES.CATEGORY_MAX, `Maks. ${SETTINGS_VALIDATION_RULES.CATEGORY_MAX} kar`),
  "5": z.string().min(SETTINGS_VALIDATION_RULES.CATEGORY_MIN, `Min. ${SETTINGS_VALIDATION_RULES.CATEGORY_MIN} kar`).max(SETTINGS_VALIDATION_RULES.CATEGORY_MAX, `Maks. ${SETTINGS_VALIDATION_RULES.CATEGORY_MAX} kar`),
});

export const settingsSchema = z.object({
  lowStockThreshold: z.number()
    .min(SETTINGS_VALIDATION_RULES.STOCK_THRESHOLD_MIN, `Minimal ${SETTINGS_VALIDATION_RULES.STOCK_THRESHOLD_MIN}`)
    .max(SETTINGS_VALIDATION_RULES.STOCK_THRESHOLD_MAX, `Maksimal ${SETTINGS_VALIDATION_RULES.STOCK_THRESHOLD_MAX}`),
  storeOverdueDays: z.number()
    .min(SETTINGS_VALIDATION_RULES.OVERDUE_DAYS_MIN, `Minimal ${SETTINGS_VALIDATION_RULES.OVERDUE_DAYS_MIN} hari`)
    .max(SETTINGS_VALIDATION_RULES.OVERDUE_DAYS_MAX, `Maksimal ${SETTINGS_VALIDATION_RULES.OVERDUE_DAYS_MAX} hari`),
  categoryLabels: categoryLabelsSchema,
  storeCategoryLabels: categoryLabelsSchema,
});

export type SettingsFormData = z.infer<typeof settingsSchema>;
